@startuml


abstract class Base {
  type A

  def show(a: A)
}


class B {
  def exec = println("Foo#exec")
}

class E1 extends Base {
  type A = A

  def show(a: E1.this.type): Unit = a.exec
}


@enduml